export type detailMedia = {
    adult: boolean,
    backdrop_path: string,
    created_by: {
        credit_id: string,
        gener: number,
        id: number,
        name: string;
        original_name: string,
        profile_path: string,
    }[],
    episode_run_time: [],
    homepage: string,
    in_production: boolean,
    langagues: string[],
    last_air_date: string,
    last_episode_to_air: {
        air_date: string,
        episode_number: number,
        episode_type: string
        id: number,
        name: string,
        overview: string,
        production_code: string,
        runtime: number,
        season_number: number,
        show_id: number,
        still_path: string,
        vote_average: number,
        vote_count: number,
    },
    network: {
        id: number,
        logo_path: string,
        name: string,
        origin_country: string,
    }[],
    next_episode_to_air: string | null,

    genre_ids: number[],
    genres: {
        id: number,
        name: string,
    }[],
    id: number,
    original_language: string,
    original_title: string,
    overview: string,
    popularity: number,
    poster_path: string,
    first_air_date: string,
    release_date: string,
    softcore: boolean,
    title: string,
    name: string,
    video: boolean,
    vote_average: number,
    vote_count: number,
    runtime: number
}